server:
  port:8080


# ActiveMQ
spring:
  application:
    name: activemq-producer
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100


