server:
  port: 8080


spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    # 连接地址
    host: 106.14.47.185
    # 端口号
    port: 5672
    # 账号
    username: guest
    # 密码
    password: guest
    # 地址
    virtual-host: /virtual_host
    # 生产者方开启消息确认的配置
    publisher-confirms: true
    publisher-returns: true

